### PR TITLE
Update to Neutrino v6 & Fix HMR with async components

### LINKED ISSUE #5: HMR is not  working
Hi,

I have cloned your project and tried, it seems HMR is not working.is it only for me.

Thanks
Kishorevarma

### PR DESCRIPTION
**Pull request by helfi92**
async component seems to have introduced a regression because [HMR is not working with System.import](https://github.com/gaearon/react-hot-loader/issues/303). I made some changes and now things seem to work seamlessly in development but are causing me to see a blank screen and a console error in production `TypeError: Cannot read property 'location' of undefined`. At the moment, I'm not sure why this issue is happening.

This PR will then resolve #5 and #6.

### CODE REVIEW

File: src/components/Bar/index.js [hunk 1]
```diff
@@ -0,0 +1,3 @@
+import { asyncComponent } from 'react-async-component';
+
+export default asyncComponent({ resolve: () => System.import('./Bar') });
```
Comment (eliperelman) [inline src/components/Bar/index.js]: `System.import()` is deprecated and is no longer going to be a thing in Webpack. Switch this to `import()`.

File: package.json [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+    "start": "neutrino start",
+    "build": "neutrino build"
+  },
+  "devDependencies": {
+    "neutrino": "^6.0.4",
+    "neutrino-preset-react": "^6.0.4"
+  },
+  "dependencies": {
+    "react": "^15.6.1",
+    "react-async-component": "^1.0.0-beta.3",
```
Comment (eliperelman) [inline package.json]: Might I recommend react-loadable instead? https://github.com/thejameskyle/react-loadable

File: src/index.js [hunk 3]
```diff
@@ -0,0 +1,21 @@
+import React from 'react';
+import { render } from 'react-dom';
+import { AppContainer } from 'react-hot-loader';
+
+import App from './App';
+
+const renderApp = () => {
+  render(
+    <AppContainer>
+      <App key={module.hot ? new Date() : undefined} />
```
Comment (eliperelman) [inline src/index.js]: Why the key?

File: src/components/Bar/index.js (hunk 1 above)
Comment (helfi92) [inline src/components/Bar/index.js]: You're right. Fixed this in the most recent commit.

File: package.json (hunk 2 above)
Comment (helfi92) [inline package.json]: Good recommendation!

File: src/index.js (hunk 3 above)
Comment (helfi92) [inline src/index.js]: It doesn't seem to hot reload properly without the key. I changed it to `key={Math.random()}` instead.

File: src/index.js [hunk 4]
```diff
@@ -7,7 +7,7 @@ import App from './App';
 const renderApp = () => {
   render(
     <AppContainer>
-      <App key={module.hot ? new Date() : undefined} />
+      <App key={Math.random()} />
```
Comment (kishorevarma) [inline src/index.js]: is there any documentation in RHL why we give random key, curious to know about it.

Comment (helfi92) [inline src/index.js]: Actually, by using `key`, I am forcing the root component to remount, thereby losing all the local state. So `key` should definitely not be used here.

I realized if I use `react-async-component` instead of `react-loadable` then HMR works (state persists). The following is the difference between the two implementations

_Using `react-loadable`_
```javascript
// src/components/Home/index.js
import Loadable from 'react-loadable';
import Loading from '../Loading';

export default Loadable({
  loader: () => import('./Home'),
  loading: Loading
});
```
_Using `react-async-component`_
```javascript
// src/components/Home/index.js
import { asyncComponent } from 'react-async-component';

export default asyncComponent({
  resolve: () => import('./Home')
});
```
I would like to believe there is a bug with `react-loadable`. Creating an issue in that repo seem to be disabled by the owner. @eliperelman are you okay if I use `react-async-component` in that case?

Comment (eliperelman) [inline src/index.js]: Absolutely!

Comment (eliperelman) [inline src/index.js]: If you know where the bug lies in react-loadable, we should get a PR over there.

Comment (helfi92) [inline src/index.js]: Awesome. I just pushed a commit :) Yeah, I'll try and see if I can find the bug in react-loadable and send them a PR.
